### ISSUE TITLE
Foundry VTT v10 support?

### ISSUE THREAD

**Issue by joevaughan** [Octarines/FoundryHourglass#11]
Hi.

Excellent module. Just wondering if you're intending to update for Foundry v10? 
I've had a look at the code and couldn't quite get my head around how the presets would work in the new DataModel (and it's use in Settings)  

Edit: Premature 'save' :D - I meant to say: I was going to do a PR but as mentioned, got a little lost with how the new datamodel would effect presets and had to give up :D

**Comment by Octarines** [comment]
Hey @joevaughan , I have been testing this module on v10 for some time (last couple of builds in fact). I only have a passing familiarity with the changes to the DataModel that you mentioned but so far the presets seem to still work. Are you experiencing a problem with them?

**Comment by Octarines** [comment]
I've just been reading round on this and according to the API documentation, the method I'm using should still work: https://foundryvtt.com/api/classes/client.ClientSettings.html. 
I wonder if the issue here is related to the word "undefined". Have you used the hourglass module before on your current installation? I'm just wondering if the validation is now checking whether the requested value from the "game.settings.get" request is null/undefined and throwing an error as a result. 
Does the module break/stop working once this error is thrown or does it continue?
It's entirely possible that I'm storing this preset data in an inappropriate place and that I should move to work with the new data model moving forward, but since it still worked in my own testing I didn't dig further.

**Comment by joevaughan** [comment]
I think it may be because I've never run hourglass on this particular FVTT world before. So there probably aren't any presets at the point the gui is calling this (they'll be populated later) and the new Data validation routines are throwing (as we say in the UK) a wobbly.

**Comment by Octarines** [comment]
Ok that makes sense now. I imagine anyone who is installing the mod for the first time will have the same issue, I'll spin up a new world on my installation later on this evening and do some testing. Hopefully I can just check if this is a first time load and initialise the setting value to some default (an empty array). Thanks for reporting this!

**Comment by Octarines** [comment]
Ok so I was able, following your instructions, to quite quickly replicate the bug. I have wrapped that game.settings.get method call in a try catch for now and log to the console the fact that no existing presets were present for the new game world in event of this error popping up. 

As I suspected, saving a preset has the effect of initialising the settings value which negates the "undefinied" error. 

I will need to do some proper research on this presets storage as I think I should probably be storing that data slightly differently to match the ideal workflows. 

I have released a hotfix (v1.5.1) which contains the fix for this bug. You should be good to go. Thanks again so much for reporting this bug. I imagine it was preventing a least a few other folk from using the module on new game worlds.

**Comment by joevaughan** [comment]
Awesome. Many thanks @Octarines :D
