### ISSUE TITLE
Documentation incomplete.

### ISSUE THREAD

**Issue by ZheakTheGeek** [Octarines/FoundryHourglass#7]
The first line of using this module, states "" To create a new hourglass, a Game Master may select the hourglass icon under the Basic Controls. This will open the options window for you to configure your hourglass. ""

There is no basic controls under module settings, or any foundry presets, which begs the question, where is this?

**The answer to this question** is that
Open the hourglass token creator, It lives inside of the "Token" selector on the left side of your screen 

https://user-images.githubusercontent.com/39840181/171923049-37876281-4604-4c58-a00e-8fd3fd0b2c58.mp4

.

**Comment by Octarines** [comment]
Thanks for noting this. I think what has happened here is that the name of the top set of controls has changed since the first iteration of Hourglass and I didn't notice. Currently the menu that Hourglass is nested under is called "Token Controls" (from the tooltip), where previously it was called "Basic Controls".
![image](https://user-images.githubusercontent.com/22074134/172474734-225a4a83-8357-4e7f-b8ed-01f5fc39aa67.png)
I will update the documentation in the next version to reflect this. In reality the Hourglass mod should live under a different (potentially its own) menu in that tools bar as it isn't actually a token. This particular job is on my to do list but not made it to the top yet.
