### ISSUE TITLE
Doubleclicking to Minimize

### ISSUE THREAD

**Issue by ZheakTheGeek** [Octarines/FoundryHourglass#8]
Double clicking to minimize or hide the timer in the default tray results in strange behaviors that keep it permanently hidden and collapsing on the tray :(

Still a beautiful module, if a bit rough around the edges!

https://user-images.githubusercontent.com/39840181/171922830-1aadf626-a937-45a5-8ade-cd822eb0962a.mp4

**Comment by ZheakTheGeek** [comment]
[](https://gyazo.com/531cd362c9be9a41006b5be2c9d1e6ab)

**Comment by ZheakTheGeek** [comment]
https://gyazo.com/531cd362c9be9a41006b5be2c9d1e6ab

**Comment by Octarines** [comment]
That's for highlighting this. I honestly just missed it in my testing.

**Comment by Octarines** [comment]
Just had a bit of a look at this. Wow it really is broken when you do this. Turns out its not just the timer windows either its the Hourglass creation window as well. I'll let you know when I've had a chance to investigate. Do you think it would be problematic if I was to attempt to disable this minimize behaviour initially (in anticipation that the fix may be more involved)?

**Comment by Octarines** [comment]
I have temporarily disabled the double click minimize functionality on hourglass mod windows (including options) until I get a chance to fix it properly. Thanks for reporting this, I have added you as contributor to the release @ZheakTheGeek. I would be keen to hear if you spot any other "rough edges" so I can get them fettled :)
